import { NgModule } from '@angular/core';
import {CommonModule} from '@angular/common';
import {
  CardModule,
  MenuModule,
  TreeModule,
  ChartModule,
  PanelModule,
  SharedModule,
  DialogModule,
  MessageModule,
  MenubarModule,
  SidebarModule,
  SpinnerModule,
  TooltipModule,
  TabViewModule,
  TabMenuModule,
  CheckboxModule,
  CarouselModule,
  MessageService,
  MessagesModule,
  TreeTableModule,
  SlideMenuModule,
  AccordionModule,
  KeyFilterModule,
  InputTextModule,
  PaginatorModule,
  TieredMenuModule,
  RadioButtonModule,
  MultiSelectModule,
  InputSwitchModule,
  AutoCompleteModule,
  OverlayPanelModule,
  SelectButtonModule,
  ToggleButtonModule,
  ProgressSpinnerModule
} from 'primeng';
import {ToastModule} from 'primeng/toast';
import {ButtonModule} from 'primeng/button';
import {TableModule} from 'primeng/table';
import {FileUploadModule} from 'primeng/fileupload';

@NgModule({
    imports: [
      MenuModule,
      TreeModule,
      CardModule,
      ChartModule,
      ToastModule,
      TableModule,
      PanelModule,
      CommonModule,
      DialogModule,
      SharedModule,
      ButtonModule,
      MessageModule,
      TooltipModule,
      SpinnerModule,
      MenubarModule,
      SidebarModule,
      TabViewModule,
      TabMenuModule,
      CheckboxModule,
      CarouselModule,
      MessagesModule,
      TreeTableModule,
      AccordionModule,
      PaginatorModule,
      InputTextModule,
      KeyFilterModule,
      SlideMenuModule,
      TieredMenuModule,
      FileUploadModule,
      InputSwitchModule,
      RadioButtonModule,
      MultiSelectModule,
      SelectButtonModule,
      AutoCompleteModule,
      OverlayPanelModule,
      ToggleButtonModule,
      ProgressSpinnerModule
  ],
  declarations: [],
  exports: [
    CommonModule,
    ToastModule,
    MenuModule,
    MenubarModule,
    SharedModule,
    ChartModule,
    CarouselModule,
    CheckboxModule,
    DialogModule,
    TooltipModule,
    PaginatorModule,
    RadioButtonModule,
    ButtonModule,
    InputTextModule,
    InputSwitchModule,
    SelectButtonModule,
    TableModule,
    TreeTableModule,
    KeyFilterModule,
    MessageModule,
    MessagesModule,
    SidebarModule,
    SlideMenuModule,
    TieredMenuModule,
    FileUploadModule,
    MultiSelectModule,
    TabMenuModule,
    AutoCompleteModule,
    CardModule,
    PanelModule,
    AccordionModule,
    OverlayPanelModule,
    SpinnerModule,
    TabViewModule,
    TreeModule,
    ProgressSpinnerModule,
    ToggleButtonModule
  ],
  providers: [
    MessageService
  ]
})
export class PrimengModule { }
