import { NgModule } from '@angular/core';
import {CommonModule} from '@angular/common';
import {
  AccordionModule,
  AutoCompleteModule,
  ButtonModule,
  CalendarModule,
  CardModule,
  CarouselModule,
  ChartModule,
  CheckboxModule,
  DialogModule,
  FileUploadModule,
  InputSwitchModule,
  InputTextModule,
  KeyFilterModule,
  MenubarModule,
  MenuModule,
  MessageModule,
  MessageService,
  MessagesModule,
  MultiSelectModule,
  OverlayPanelModule,
  PaginatorModule,
  PanelModule, ProgressSpinnerModule,
  RadioButtonModule,
  SelectButtonModule,
  SharedModule,
  SidebarModule,
  SlideMenuModule,
  SpinnerModule,
  TabMenuModule,
  TabViewModule,
  TieredMenuModule,
  ToggleButtonModule,
  TooltipModule,
  TreeModule,
  TreeTableModule
} from 'primeng/primeng';
import {ToastModule} from 'primeng/toast';
import {TableModule} from 'primeng/table';

@NgModule({
    imports: [
    CommonModule,
    ToastModule,
    SharedModule,
    ChartModule,
    MenuModule,
    CarouselModule,
    MenubarModule,
    SlideMenuModule,
    TieredMenuModule,
    FileUploadModule,
    CheckboxModule,
    DialogModule,
    RadioButtonModule,
    CalendarModule,
    TooltipModule,
    PaginatorModule,
    ButtonModule,
    InputTextModule,
    InputSwitchModule,
    SelectButtonModule,
    TableModule,
    TreeTableModule,
    KeyFilterModule,
    MessageModule,
    MessagesModule,
    SidebarModule,
    MultiSelectModule,
    TabMenuModule,
    AutoCompleteModule,
    CardModule,
    PanelModule,
    AccordionModule,
    OverlayPanelModule,
    SpinnerModule,
    TabViewModule,
    TreeModule,
    ProgressSpinnerModule,
    ToggleButtonModule
  ],
  declarations: [],
  exports: [
    CommonModule,
    ToastModule,
    MenuModule,
    MenubarModule,
    SharedModule,
    ChartModule,
    CarouselModule,
    CheckboxModule,
    DialogModule,
    CalendarModule,
    TooltipModule,
    PaginatorModule,
    RadioButtonModule,
    ButtonModule,
    InputTextModule,
    InputSwitchModule,
    SelectButtonModule,
    TableModule,
    TreeTableModule,
    KeyFilterModule,
    MessageModule,
    MessagesModule,
    SidebarModule,
    SlideMenuModule,
    TieredMenuModule,
    FileUploadModule,
    MultiSelectModule,
    TabMenuModule,
    AutoCompleteModule,
    CardModule,
    PanelModule,
    AccordionModule,
    OverlayPanelModule,
    SpinnerModule,
    TabViewModule,
    TreeModule,
    ProgressSpinnerModule,
    ToggleButtonModule
  ],
  providers: [
    MessageService
  ]
})
export class PrimengModule { }
