spring:
  # for Postgres database
  datasource:
    url: "jdbc:postgresql://${db-host}:5432/stockOptions"
    username: ${db-user}
    password:  ${db-pw}

  # for Ms SQL server database
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #url: jdbc:sqlserver://${db-host}: 1433;DatabaseName=jwt
    #username: ${db-user}
    #password: ${db-pw}
  jpa:
    hibernate:
      ddl-auto: update
quartz:
  enabled: true
jwt:
  header: Authorization
  secret: secret-key
